server:
  port: 9000
spring:
  kafka:
    bootstrap-servers: www.wglgg.cn:9092
    template:
      default-topic: msg2tts
    consumer:
      group-id: wglgg
    listener:
      concurrency: 3
    producer:
      batch-size: 1000
